option(${PROJECT_NAME}_ENABLE_CLANG_TIDY "Enable clang-tidy" OFF)
option(${PROJECT_NAME}_ENABLE_CPPCHECK "Enable cppcheck" OFF)

if(${PROJECT_NAME}_ENABLE_CLANG_TIDY AND NOT ("thread" IN_LIST ${PROJECT_NAME}_SANITIZER))
  find_program(CLANGTIDY clang-tidy)
  if(CLANGTIDY)
    set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} --extra-arg=-Wno-unknown-warning-option)
  else()
    message(WARNING "clang-tidy not found")
  endif()
endif()

if(${PROJECT_NAME}_ENABLE_CPPCHECK)
  find_program(CPPCHECK cppcheck)
  if(CPPCHECK)
    set(CMAKE_CXX_CPPCHECK ${CPPCHECK} --suppress=missingInclude --enable=all
                           --inline-suppr --inconclusive)
  else()
    message(WARNING "cppcheck not found")
  endif()
endif()
